#!/bin/sh
### BEGIN INIT INFO
# Provides:          Set Date
# Required-Start:    
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Init Service to set the current year
# Description:       Init Service to set the current year. Needed for non HW-Clock Systems
### END INIT INFO

#Init Priority
# Start:			 10
# Stop:				 30

#Variables
NAME=SET-DATE
DATE=2016-07-10
DAEMON=Set-Date
DAEMON_PATH=/home/apps
DESC="Init Service to set the current year"
SCRIPTNAME=/etc/init.d/$NAME
 
# Actions
case "$1" in
    start)
        #printf "%-50s" "$NAME to $DATE ..."
        #cd $DAEMON_PATH
        #printf "%s\n" "Ok"
        #./$NAME >> Hello.txt & 
        printf "%s\n" "$NAME to $DATE ..."
	date --set $DATE &&
		printf "%s\n" "Ok"
      	;;
    stop)
       	#printf "%-50s\n" "Stopping $NAME"
       	#cd $DAEMON_PATH
        #killall $NAME & 
        printf "%-50s" "Shutdown Set-Date"
        printf "%s\n" "Ok"
        ;;
   *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
   
