#!/bin/sh
### BEGIN INIT INFO
# Provides:          Load XBEE Module
# Required-Start:    
# Required-Stop:    
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Init Service to load the XBEE Module
# Description:       Init Service to load the FTDI UART to USB Bridge for the XBEE Module
### END INIT INFO

#Init Priority
# Start:			 20
# Stop:				 30

#Variables
NAME=XBEE-Module
DAEMON=XBEE-Module
DAEMON_PATH=/home/apps
DESC="Init Service to load the XBEE Module"
SCRIPTNAME=/etc/init.d/$NAME
 
# Actions
case "$1" in
    start)
        #printf "%-50s" "Starting $NAME..."
        #cd $DAEMON_PATH
        #printf "%s\n" "Ok"
        #./$NAME >> Hello.txt & 
        printf "%s\n" "Loading FTDI USB to UART Bridge"
        modprobe ftdi_sio vendor=0x403 product=0x6001 &
		printf "%s\n" "Ok"
        ;;
   stop)
       	#printf "%-50s\n" "Stopping $NAME"
       	#cd $DAEMON_PATH
        #killall $NAME & 
        printf "%-50s" "Unload FTDI USB to UART Bridge"
        modprobe -r ftdi_sio &  
        printf "%s\n" "Ok"
        ;;
   *)
        echo "Usage: $0 {start|stop}"
        exit 1
esac
   
